### ISSUE TITLE
Build Fails on Zig Master

### ISSUE THREAD

**Issue by UnsaltedScholar** [cjRem44x/Fl4p_b0x#1]
Currently, the project fails to build with the below error on zig master (0.16.0-dev.1912+0cbaaa5eb). If I recall correctly, the trimLeft (and related functions) were renamed/reworked in a more recent 0.16.x version. 

```
/home/username/.cache/zig/p/raylib-5.6.0-dev-whq8uCg2ywTzCiX3VEP9RuCMXR6_VnDBmkj8GjL_p5QN/build.zig:109:27: error: root source file struct 'mem' has no member named 'trimLeft'
        var flag = std.mem.trimLeft(u8, line, " \t"); // Trim whitespace
                   ~~~~~~~^~~~~~~~~
/home/username/src/zig-x86_64-linux-0.16.0-dev.1912+0cbaaa5eb/lib/std/mem.zig:1:1: note: struct declared here
const std = @import("std.zig");
^~~~~
referenced by:
    compileRaylib: /home/username/.cache/zig/p/raylib-5.6.0-dev-whq8uCg2ywTzCiX3VEP9RuCMXR6_VnDBmkj8GjL_p5QN/build.zig:176:21
    build: /home/username/.cache/zig/p/raylib-5.6.0-dev-whq8uCg2ywTzCiX3VEP9RuCMXR6_VnDBmkj8GjL_p5QN/build.zig:495:34
    11 reference(s) hidden; use '-freference-trace=13' to see all references
/home/username/.cache/zig/p/raylib_zig-5.6.0-dev-KE8REL5MBQAf3p497t52Xw9P7ojndIkVOWPXnLiLLw2P/build.zig:403:16: error: no field or member function named 'linkLibC' in 'Build.Step.Compile'
    raylib_test.linkLibC();
    ~~~~~~~~~~~^~~~~~~~~
/home/username/src/zig-x86_64-linux-0.16.0-dev.1912+0cbaaa5eb/lib/std/Build/Step/Compile.zig:1:1: note: struct declared here
const Compile = @This();
^~~~~
/home/username/.cache/zig/p/raylib_zig-5.6.0-dev-KE8REL5MBQAf3p497t52Xw9P7ojndIkVOWPXnLiLLw2P/build.zig:403:16: note: method invocation only supports up to one level of implicit pointer dereferencing
/home/username/.cache/zig/p/raylib_zig-5.6.0-dev-KE8REL5MBQAf3p497t52Xw9P7ojndIkVOWPXnLiLLw2P/build.zig:403:16: note: use '.*' to dereference pointer
build.zig:95:8: error: no field or member function named 'linkLibrary' in 'Build.Step.Compile'
    exe.linkLibrary(raylib_artifact);
    ~~~^~~~~~~~~~~~
/home/username/src/zig-x86_64-linux-0.16.0-dev.1912+0cbaaa5eb/lib/std/Build/Step/Compile.zig:1:1: note: struct declared here
const Compile = @This();
^~~~~
build.zig:95:8: note: method invocation only supports up to one level of implicit pointer dereferencing
build.zig:95:8: note: use '.*' to dereference pointer
```

**Comment by UnsaltedScholar** [comment]
Closing as stale
